job('First-Maven-Project-Via-DSL') {
 description("First Maven job generated by the DSL ON ${new Date()}")
 scm {
  git("https://github.com/younesAmin/mvn-hello-world-war.git", 'main')
 }
 steps {
  maven('clean package')
 }
 publishers {
  // archive the war file generated
  archiveArtifacts '**/*.jar'
 }
}
