job('First-Maven-Project-Via-DSL') {
 description("First Maven job generated by the DSL ON ${new Date()}")
 scm {
  git("git@github.com:younesAmin/labjobDSL.git", main)
 }
 triggers {
 scm('* * * * *')
 }
 steps {
  maven('clean package')
 }
 publishers {
  // archive the war file generated
  archiveArtifacts '**/*.jar'
 }
}
